server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    platform: postgres
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
