server:
  error:
    include-stacktrace: never

spring:
  datasource:
    uurl: ${JDBC_DATABASE_URL}
      username: ${JDBC_DATABASE_USERNAME}
      password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      hbm2ddl:
        auto: update